
export default {

ADD_BOOK: 	         'ADD_BOOK',
DELETE_BOOK: 	     'DELETE_BOOK',
EDIT_BOOK: 	         'EDIT_BOOK',
FETCH_BOOKS:         'FETCH_BOOKS',
FETCH_BOOKS_SUCCESS: 'FETCH_BOOKS_SUCCESS',
FETCH_BOOKS_FAILED:  'FETCH_BOOKS_FAILED',
ORDER_BOOK:          'ORDER_BOOK',
OPEN_MODAL:          'OPEN_MODAL',
CLOSE_MODAL:         'CLOSE_MODAL',
OPEN_DELETE_BOOK_MODAL: 'OPEN_DELETE_BOOK_MODAL',
CLOSE_DELETE_BOOK_MODAL: 'CLOSE_DELETE_BOOK_MODAL',
}